[[SCS_MKL]]
arch = "x86_64"
git-tree-sha1 = "7d743b271dc13caf8e6ecba484b0b54a12f0e5a0"
libc = "glibc"
os = "linux"

    [[SCS_MKL.download]]
    sha256 = "b11077e7e3d53467c8bf708f63b14b2185187d34d5545f6e577811fa7324518e"
    url = "https://github.com/JuliaBinaryWrappers/SCS_MKL_jll.jl/releases/download/SCS_MKL-v300.200.1000+0/SCS_MKL.v300.200.1000.x86_64-linux-gnu.tar.gz"
