[[SCS_MKL]]
arch = "x86_64"
git-tree-sha1 = "48d881be66214a024183d8e22fc840dbc0c8087a"
libc = "glibc"
os = "linux"

    [[SCS_MKL.download]]
    sha256 = "a814e49c5f3b6f242c64e6569b91110d79908117b07b99a2f54b83635797bea5"
    url = "https://github.com/JuliaBinaryWrappers/SCS_MKL_jll.jl/releases/download/SCS_MKL-v300.200.1100+0/SCS_MKL.v300.200.1100.x86_64-linux-gnu.tar.gz"
