[[SCS_MKL]]
arch = "x86_64"
git-tree-sha1 = "28990429b3b72d0ce7d7855567ab3274534bc5a9"
libc = "glibc"
os = "linux"

    [[SCS_MKL.download]]
    sha256 = "b6b3e01ebffdbf0055b1adcddab81684211ce6fecee582d96c76a9f054b97cb9"
    url = "https://github.com/JuliaBinaryWrappers/SCS_MKL_jll.jl/releases/download/SCS_MKL-v3.2.9+0/SCS_MKL.v3.2.9.x86_64-linux-gnu.tar.gz"
