[[SCS_MKL]]
arch = "x86_64"
git-tree-sha1 = "a1393515da0387b99e2a990045f2d58ec1394b1b"
libc = "glibc"
os = "linux"

    [[SCS_MKL.download]]
    sha256 = "df526600313b7785a07c3059e2443be08de09662753ac7a8b943e2a77ba61fc3"
    url = "https://github.com/JuliaBinaryWrappers/SCS_MKL_jll.jl/releases/download/SCS_MKL-v300.200.900+0/SCS_MKL.v300.200.900.x86_64-linux-gnu.tar.gz"
